### ISSUE TITLE
NullPointerException in PreferenceSectionAdapter.filter

### ISSUE THREAD

**Issue by TheAndroidMaster** [TheAndroidMaster/Status#84]
<details>

```
java.lang.NullPointerException
	at com.james.status.adapters.PreferenceSectionAdapter.filter(PreferenceSectionAdapter.java:107)
	at com.james.status.fragments.GeneralPreferenceFragment.filter(GeneralPreferenceFragment.java:253)
	at com.james.status.adapters.SimplePagerAdapter.filter(SimplePagerAdapter.java:64)
	at com.james.status.activities.MainActivity$9.onQueryTextChange(MainActivity.java:209)
```

</details>

**Comment by TheAndroidMaster** [comment]
3 reports so far, but not everybody reports the crashes when they happen. I'm not completely sure why I didn't pick this up during testing, but whatever... (maybe I should be using unit tests for this lol)
