### ISSUE TITLE
android.app.RemoteServiceException: can't deliver broadcast

### ISSUE THREAD

**Issue by TheAndroidMaster** [TheAndroidMaster/Status#92]
Noooo clue what this means, what's causing it, or why it's happening. Stack trace below :P 
<details>

```
com.james.status E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.james.status, PID: 3314
    android.app.RemoteServiceException: can't deliver broadcast
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6316)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

</details>

**Comment by itaishalom** [comment]
Hi, I had this issue too. I found out the I broadcast on the intent huge amount of data (which was a big byte array..) So I solved it by decreasing the size of the byte array. Check it out!

**Comment by TheAndroidMaster** [comment]
@itaishalom is this in your own project or a fork of the app, and if so could you make a PR? Would help me out a ton :smile:

**Comment by itaishalom** [comment]
Hi, I am unrelated to this. I just had similar issue and googled it, somehow I found this thread so I post my answer .
